name: base
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py39haa95532_0
  - cffi=1.14.6=py39h2bbff1b_0
  - chardet=4.0.0=py39haa95532_1003
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.10.3=py39haa95532_0
  - conda-package-handling=1.7.3=py39h8cc25b3_1
  - console_shortcut=0.1.1=4
  - cryptography=3.4.7=py39h71e12ea_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - ipykernel=6.4.1=py39haa95532_1
  - ipython=7.29.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39haa95532_7
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libpng=1.6.37=h2a8f88b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - menuinst=1.4.16=py39h2bbff1b_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py39haa95532_0
  - openssl=1.1.1l=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.3=py39haa95532_0
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pycosat=0.6.3=py39h2bbff1b_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.5=h6244533_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=228=py39he774522_0
  - pywinpty=0.5.7=py39haa95532_0
  - pyzmq=22.2.1=py39hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py39h2bbff1b_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - yaml=0.2.5=he774522_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - cycler==0.11.0
    - fonttools==4.28.2
    - kiwisolver==1.3.2
    - matplotlib==3.5.0
    - numpy==1.21.4
    - pillow==8.4.0
    - scipy==1.7.3
    - setuptools-scm==6.3.2
    - tomli==1.2.2
